name: Markdown Validator
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      statuscheck:
        description: "Output of markdown validation job"
        value: ${{ jobs.MD-Linter-Action.outputs.job_status }}

jobs:
  MD-Linter-Action:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      job_status: ${{ steps.markdown_lint.outputs.JobStatus }}
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Creating new temp sub dir called `tools`
        run: |
          mkdir -m 777 tools
      - name: Check out ${{ github.repository }} Repo code at ${{ github.workspace }}
        uses: actions/checkout@main
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: ${{ github.workspace }}
      - name: Check out Fiserv/remote-actions Repo code at ${{ github.workspace }}/tools
        uses: actions/checkout@main
        with:
          repository: Fiserv/remote-actions
          ref: TFDS-1530-Direct-Link-Validator
          path: ${{ github.workspace }}/tools
      - name: List files in the repository
        run: |
          cd ${{ github.workspace }}
          pwd
          ls -la
          cd ${{ github.workspace }}/tools
          pwd
          ls -la
      - run: echo "üí° The ${{ github.repository }} repository has been cloned on root"
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@main
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Running Markdown Linter.....
        id: markdown_lint
        run: |
          cd ${{ github.workspace }}/tools/scripts
          ls -la
          npmv=$(npm --version)
          echo "NPM version installed : " $npmv
          nodev=$(node --version)
          echo "Node version installed : " $nodev
          npm install
          echo " Repo: ${{ github.repository }}"
          echo " Space: ${{ github.workspace }}"
          result=$(npm run markdownlint ${{ github.workspace }})
          echo "**********TEST RESULTS*********************"
          echo "$result"
          if [[ $result == *'VALIDATOR FAILED'* ]] ;then
            echo "Validator failed and exiting the Job..."
            exit 1 
          elif [[ $result == *'PASSED'* ]] ;then
            echo "Validator Ran Successfully....üçè"
          fi
      - run: echo "üçè This job's status is ${{ job.status }} and output - ${{ steps.markdown_validate.outputs.JobStatus }}"
